[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chapters"
version = "0.1.0"
description = "module for importing chapters"

dependencies = []

[tool.setuptools.packages.find]
where = ["."]
